blank_issues_enabled: true
contact_links:
  - name: Kronein Core Security Policy
    url: https://github.com/marcofortina/kronein/blob/master/SECURITY.md
    about: View security policy
  - name: Kronein Core Project
    url: https://github.com/marcofortina/kronein
    about: Kronein Core repository
