// Copyright (c) The Bitcoin Core developers
// Copyright (c) 2026 The Kronein Core developers
// Distributed under the MIT software license, see the accompanying
// file COPYING or https://opensource.org/license/mit.

#ifndef BITCOIN_CHAINPARAMSSEEDS_H
#define BITCOIN_CHAINPARAMSSEEDS_H
#include <array>

/**
 * List of fixed seed nodes for the Kronein network
 * AUTOGENERATED by contrib/seeds/generate-seeds.py
 *
 * Each line contains a BIP155 serialized (networkID, addr, port) tuple.
 */
static constexpr std::array<uint8_t, 0> chainparams_seed_main{{
}};

static constexpr std::array<uint8_t, 0> chainparams_seed_testnet4{{
}};
#endif // BITCOIN_CHAINPARAMSSEEDS_H
