# TEMPORARY: one original CI job at a time; restore workflow from 44062df9c6928148dfd23cfb4a094c4b90b1a3fb
# Copyright (c) 2023-present The Bitcoin Core developers
# Copyright (c) 2026 The Kronein Core developers
# Distributed under the MIT software license, see COPYING.
name: CI
'on':
  pull_request: null
  push:
    branches:
      - '**'
    tags-ignore:
      - '**'
  workflow_dispatch: {}
concurrency:
  group: ci-isolation-${{ github.ref }}
  cancel-in-progress: false
env:
  CI_FAILFAST_TEST_LEAVE_DANGLING: 1
  REPO_USE_WARP_RUNNERS: bitcoin/bitcoin
defaults:
  run:
    shell: bash
jobs:
  runners:
    name: '[meta] determine runners'
    runs-on: ubuntu-slim
    outputs:
      provider: ${{ steps.runners.outputs.provider }}
    steps:
      - name: Annotate with pull request number
        run: |
          if [ "${{ github.event_name }}" = "pull_request" ]; then
            echo "::notice title=debug_pull_request_number_str::${{ github.event.number }}"
          fi
      - id: runners
        run: |
          if [[ "${REPO_USE_WARP_RUNNERS}" == "${{ github.repository }}" ]]; then
            echo "provider=warp" >> "$GITHUB_OUTPUT"
            echo "::notice title=Runner Selection::Using Warp Runners"
          else
            echo "provider=gha" >> "$GITHUB_OUTPUT"
            echo "::notice title=Runner Selection::Using GitHub-hosted runners"
          fi
  ci-matrix:
    name: ${{ matrix.name }}
    needs: runners
    runs-on: ${{ needs.runners.outputs.provider == 'warp' && matrix.warp-runner || matrix.fallback-runner }}
    if: ${{ vars.SKIP_BRANCH_PUSH != 'true' || github.event_name == 'pull_request' }}
    timeout-minutes: ${{ matrix.timeout-minutes }}
    env:
      DANGER_CI_ON_HOST_FOLDERS: 1
      FILE_ENV: ${{ matrix.file-env }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - name: No wallet
            warp-runner: warp-ubuntu-latest-x64-4x
            fallback-runner: ubuntu-latest
            timeout-minutes: 120
            file-env: ./ci/test/00_setup_env_native_nowallet.sh
    steps:
      - name: Annotate with pull request number
        run: |
          if [ "${{ github.event_name }}" = "pull_request" ]; then
            echo "::notice title=debug_pull_request_number_str::${{ github.event.number }}"
          fi
      - name: Checkout
        uses: actions/checkout@v6
        with:
          ref: ${{ github.event_name == 'pull_request' && github.ref || '' }}
      - name: Configure environment
        uses: ./.github/actions/configure-environment
      - name: Restore caches
        id: restore-cache
        uses: ./.github/actions/cache/restore
        with:
          provider: ${{ matrix.provider || needs.runners.outputs.provider }}
      - name: Configure Docker
        uses: ./.github/actions/configure-docker
        with:
          provider: ${{ matrix.provider || needs.runners.outputs.provider }}
      - name: Clear unnecessary files
        if: ${{ needs.runners.outputs.provider == 'gha' && true || false }}
        uses: ./.github/actions/clear-files
      - name: Enable bpfcc script
        if: ${{ env.CONTAINER_NAME == 'ci_native_asan' }}
        run: sed -i "s|\${INSTALL_BCC_TRACING_TOOLS}|true|g" ./ci/test/00_setup_env_native_asan.sh
      - name: Set mmap_rnd_bits
        if: ${{ env.CONTAINER_NAME == 'ci_native_tsan' || env.CONTAINER_NAME == 'ci_native_msan' || env.CONTAINER_NAME == 'ci_native_fuzz_msan' }}
        run: sudo sysctl -w vm.mmap_rnd_bits=28
      - name: CI script
        run: ./ci/test_run_all.sh
      - name: Save caches
        uses: ./.github/actions/cache/save
        with:
          provider: ${{ matrix.provider || needs.runners.outputs.provider }}
