# TEMPORARY: one original CI job at a time; restore workflow from 44062df9c6928148dfd23cfb4a094c4b90b1a3fb
# Copyright (c) 2023-present The Bitcoin Core developers
# Copyright (c) 2026 The Kronein Core developers
# Distributed under the MIT software license, see COPYING.
name: CI
'on':
  pull_request: null
  push:
    branches:
      - '**'
    tags-ignore:
      - '**'
  workflow_dispatch: {}
concurrency:
  group: ci-isolation-${{ github.ref }}
  cancel-in-progress: false
env:
  CI_FAILFAST_TEST_LEAVE_DANGLING: 1
  REPO_USE_WARP_RUNNERS: bitcoin/bitcoin
defaults:
  run:
    shell: bash
jobs:
  macos-native-arm64:
    name: ${{ matrix.job-name }}
    runs-on: macos-15
    if: ${{ vars.SKIP_BRANCH_PUSH != 'true' || github.event_name == 'pull_request' }}
    timeout-minutes: ${{ matrix.timeout-minutes }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - job-type: fuzz
            file-env: ./ci/test/00_setup_env_mac_native_fuzz.sh
            job-name: macOS native, fuzz
            timeout-minutes: 120
    env:
      DANGER_RUN_CI_ON_HOST: 1
      BASE_ROOT_DIR: ${{ github.workspace }}/repo_archive
    steps:
      - name: Annotate with pull request number
        run: |
          if [ "${{ github.event_name }}" = "pull_request" ]; then
            echo "::notice title=debug_pull_request_number_str::${{ github.event.number }}"
          fi
      - name: Checkout
        uses: actions/checkout@v6
        with:
          ref: ${{ github.event_name == 'pull_request' && github.ref || '' }}
      - name: Clang version
        run: |
          # Use the latest Xcode supported by the version of macOS denoted in
          # doc/release-notes-empty-template.md and providing at least the
          # minimum clang version denoted in doc/dependencies.md.
          # See: https://developer.apple.com/documentation/xcode-release-notes/xcode-16_2-release-notes
          sudo xcode-select --switch /Applications/Xcode_16.2.app
          clang --version
      - name: Install Homebrew packages
        env:
          HOMEBREW_NO_INSTALLED_DEPENDENTS_CHECK: 1
        run: |
          # A workaround for "The `brew link` step did not complete successfully" error.
          brew install --quiet python@3 || brew link --overwrite python@3
          brew install --quiet coreutils ninja pkgconf ccache boost libevent zeromq qt@6 qrencode capnp
      - name: Set Ccache directory
        run: echo "CCACHE_DIR=${RUNNER_TEMP}/ccache_dir" >> "$GITHUB_ENV"
      - name: Restore Ccache cache
        id: ccache-cache
        uses: actions/cache/restore@v5
        with:
          path: ${{ env.CCACHE_DIR }}
          key: ${{ github.job }}-${{ matrix.job-type }}-ccache-${{ github.run_id }}
          restore-keys: ${{ github.job }}-${{ matrix.job-type }}-ccache-
      - name: Create git archive
        run: |
          git log -1
          git archive --format=tar --prefix=repo_archive/ --output=repo.tar HEAD
          tar -xf repo.tar
      - name: CI script
        run: |
          cd repo_archive
          ./ci/test_run_all.sh
        env:
          FILE_ENV: ${{ matrix.file-env }}
      - name: Save Ccache cache
        uses: actions/cache/save@v5
        if: github.event_name != 'pull_request' && github.ref_name == github.event.repository.default_branch && steps.ccache-cache.outputs.cache-hit != 'true'
        with:
          path: ${{ env.CCACHE_DIR }}
          key: ${{ github.job }}-${{ matrix.job-type }}-ccache-${{ github.run_id }}
